### ISSUE TITLE
When using with merged fields it throwns an error.

### ISSUE THREAD

**Issue by jeffreydevreede** [dkulyk/nova-tabs#1]
Am trying to use this in combination with a resource where I extracted a part of the fields to its own method and used `merge`, as shown [here](https://nova.laravel.com/docs/1.0/resources/fields.html#place-field).
The error that I am getting is:
```
Call to undefined method Illuminate\Http\Resources\MergeValue::withMeta()
```
on https://github.com/dkulyk/nova-tabs/blob/master/src/Tabs.php#L56

**Comment by dkulyk** [comment]
Fixed in v1.1.2
