### ISSUE TITLE
Enhancement: Tabs in Edit view

### ISSUE THREAD

**Issue by ahmedkandel** [dkulyk/nova-tabs#10]
@dkulyk thanks for the great robust package, are you planning to add support for edit view? if so it will be also great if validation in edit view swich to the tab containing invalid fields ;)

**Comment by dkulyk** [comment]
In this implementation it is impossible. I'll try to implement it when Panels on edit views will be added.

**Comment by ahmedkandel** [comment]
@dkulyk thanks a lot looking forward to that.

**Comment by ahmedkandel** [comment]
Hi @dkulyk, Nova 2.0.8 has been released with "Panels on the Create and Update views" will it be possible to the tabs as well?

Thanks.
