### ISSUE TITLE
Panels within tabs

### ISSUE THREAD

**Issue by 4unkur** [dkulyk/nova-tabs#15]
I might guess it's impossible to have a standard Panels within Tabs, right?  
Any ideas how can I achieve something similar? I need to somehow separate a long list of fields. Tabs will be too much, just visual separation needed.

**Comment by dkulyk** [comment]
You may use [heading-field](https://nova.laravel.com/docs/1.0/resources/fields.html#heading-field)

**Comment by 4unkur** [comment]
Thanks. I figured it out. I created my own field, which look nicer )  
Thanks again
