### ISSUE TITLE
Pagination settings for rows in HasMany grid

### ISSUE THREAD

**Issue by asilverstein** [dkulyk/nova-tabs#17]
Currently the pagination is fixed to 5 rows per page for HasMany grids. Is this configurable?

![tabs-hasmany-pagination](https://user-images.githubusercontent.com/440978/65259089-1ca3e080-dad2-11e9-8a44-2ba0c677f778.png)

**Comment by asilverstein** [comment]
I found the setting `$perPageViaRelationship`, which works. But I would actually like to show the Filters funnel that gives all the filter options (as well as pagination options). Is that possible?

**Comment by dkulyk** [comment]
This is not Tabs component. Use Laravel Nova documentation.

**Comment by asilverstein** [comment]
Is it possible to show the filters for a resource that lives inside a tab?
