### ISSUE TITLE
showToolbar() doen't work

### ISSUE THREAD

**Issue by bajramemini** [dkulyk/nova-tabs#2]
Hello

Cool what you did with my package. I am considering simplifying some stuff too.

When I do:

```php
(new Tabs('Tabs', [
    // ...
]))->showToolbar(),
```

It doesn't work. There is no showToolbar-function in Tabs.php yet.

Regards

**Comment by dkulyk** [comment]
I has fixed readme. You should use `withToolbar()` method.
