### ISSUE TITLE
Tabs Labels

### ISSUE THREAD

**Issue by Yelles** [dkulyk/nova-tabs#4]
Hi,

First, thanks for this usefull package!

This is not working :

```
new Tabs('Tabs', [
                HasMany::make('Address List', 'TierAddress'),
            ]),
```

I tried this too, without luck :

```
new Tabs('Tabs', [
                new Panel('Adress List 1', [
                    HasMany::make('TierAddress'),
                ]),
                'Adress List 2' => [
                    HasMany::make('TierAddress'),
                ],
            ]),
```

I'm looking to rename the **create TierAddress** Button & **TierAddress** Tabs Label.
Any way to use the singularLabel and/or label of the ressource ?

**Comment by dkulyk** [comment]
You need to use Nova 1.3+ and update resources `php artisan nova:publish`

```php
new Tabs('Relations', [ 
    HasMany::make('TabName', 'TierAddress', AddressResource::class)
        ->singularLabel('Address') // This will shown in Create button
]),
```

**Comment by Yelles** [comment]
> You need to use Nova 1.3+ and update resources `php artisan nova:publish`
> 
> ```
> new Tabs('Relations', [ 
>     HasMany::make('TabName', 'TierAddress', AddressResource::class)
>         ->singularLabel('Address') // This will shown in Create button
> ]),
> ```

so trivial, I feel stupid! thank you so much
