### ISSUE TITLE
Tabs (Panel) Title without Ressource Buttons

### ISSUE THREAD

**Issue by Yelles** [dkulyk/nova-tabs#7]
I saw that the only way to display the Panel title on the created Tabs is to add `->withToolbar()` parameter.

<img width="1015" alt="cleanshot 2019-02-11 at 12 48 41 2x" src="https://user-images.githubusercontent.com/689478/52561351-6ff6d780-2dfb-11e9-9824-003f8b8d534b.png">

If i remove `->withToolbar()`, the title is gone :

<img width="1007" alt="cleanshot 2019-02-11 at 12 55 37 2x" src="https://user-images.githubusercontent.com/689478/52561687-6883fe00-2dfc-11e9-9ff2-f9b4530ef082.png">

For a panel, adding `->withToolbar()` only adds the Ressource Buttons.
If i remove `->withToolbar()` from a Panel, the title remains, that's the behavior I'm looking for.

Any idea about that ?

Thanks again for your help

**Comment by dkulyk** [comment]
Added `hideLabel()` method. By default, the label will be displayed.

**Comment by Yelles** [comment]
> Added `hideLabel()` method. By default, the label will be displayed.

great, many thanks again ;)
